### ISSUE TITLE
container won't start

### ISSUE THREAD

**Issue by constantx** [ainoya/docker-sixpack#1]
keep getting this from both Kiteomatic and Tutum (docker host)

```
Redirecting to /bin/systemctl start  sshd.service
Failed to get D-Bus connection: No connection to service manager.
```

The run command from the image config appears to be:

```
/bin/sh -c "service sshd start && service redis start && service td-agent start && supervisord -c /etc/supervisord.conf"
```

Any hint on how to get started?

**Comment by ainoya** [comment]
@constantx  Sorry I stop to use `sshd` and `service` command by simple solution.
I fixed this issue, so please try again with latest docker image or build on the latest master branch?
https://registry.hub.docker.com/u/ainoya/sixpack/

**Comment by constantx** [comment]
seems to be running :)

Any tip on how to get to the web dashboard? Can't tell which port it's running on :)
