### ISSUE TITLE
what's the purpose of exposing port 24224?

### ISSUE THREAD

**Issue by constantx** [ainoya/docker-sixpack#4]

**Comment by ainoya** [comment]
For use https://github.com/ainoya/fluent-plugin-sixpack .

**Comment by constantx** [comment]
> To get A/B test statistics, this plugin forwards logs to Sixpack server.

I thought the sixpack server already keeping track of experiement statistic?

**Comment by ainoya** [comment]
> I thought the sixpack server already keeping track of experiement statistic?

That's correct. but this plugin isn't for its purpose.
This plugin(of fluentd) made for generating sixpack api requests from  general web application logs which includes experiment data.

**Comment by constantx** [comment]
:+1:
